### ISSUE TITLE
Code gen for an expression

### ISSUE THREAD

**Issue by cheshmi** [pnnl/COMET#53]
How can I generate code for `A(i,l) = B(i,j) * C(j,k) * D(k,l)` where `B` is sparse CSR.

**Comment by pthomadakis** [comment]
There was a bug that would not let us generate code for this expression. It is fixed now. 
Please pull the newest version.

I have also added an example here:
https://github.com/pnnl/COMET/blob/master/integration_test/compound_exps/CSR_Dense_chain_mult_matrix.ta 

Please let me know if you are still experiencing issues.

**Comment by cheshmi** [comment]
Thanks, is there anyway to get the equivalent C++ code of the expression?

**Comment by pthomadakis** [comment]
No, unfortunately there is not straightforward way to generate C/C++ code.

**Comment by cheshmi** [comment]
Thank you.
