### ISSUE TITLE
Multi file read breaks in containers and Rust

### ISSUE THREAD

**Issue by rizwanashraf** [pnnl/COMET#9]
The new interface (#8) for reading sparse matrices/tensors breaks when doing multiple files in containers (Docker) and Rust.

This may be happening due to reordering of runtime calls breaking expected behavior.

**Comment by rdfriese** [comment]
I was thinking we could maybe implement a simple hashmap of filename -> (file tuple) ? And basically keep the rest of the logic the same?

**Comment by rizwanashraf** [comment]
As suggested in https://github.com/pnnl/COMET/issues/9#issuecomment-1445156727, the following commit 1c5c0985c9c01977532ee2ef8d4dd954eeaa1dde fixes this issue.

Updated Rust tests to include multi-file reads in following commit: 065b4b21fb061b97e9744b869c7fdbd97d5d10c2
